### ISSUE TITLE
ERROR in ./node_modules/ng-cast/index.ts

### ISSUE THREAD

**Issue by fitnexus** [dahfazz/ngCast#4]
Hi i'm receiving the following error message. I've followed the steps to install the plugin using npm install ng-cast. i've declared NgCastModule in my app.module and I keep getting this error. Please could you help.

ERROR in ./node_modules/ng-cast/index.ts
[ng] Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
[ng] Error: /Users/../newapp/node_modules/ng-cast/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
[ng] The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
[ng]     at AngularCompilerPlugin.getCompiledFile (/Users/../newapp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
[ng]     at plugin.done.then (/Users/../newapp/node_modules/@ngtools/webpack/src/loader.js:41:31)
[ng]     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by fitnexus** [comment]
i've figured it out, to resolve this issue the following needs to be added to the tsconfig.app.json file 
```
"include" : [
    "node_modules/ng-cast/index.ts",
    "node_modules/ng-cast/ng.cast.module.ts",
    "node_modules/ng-cast/ng-cast.component.ts",
    "node_modules/ng-cast/shared/ng-cast.service.ts"
]

and then instead of calling the NgCastModule in the app.module.ts i called it in my shared.module.is for imports and exports. for some reason it wasn't working when i declared it in app.module.ts 
```
